# docker-compose.yml
server:
  image: postgrest/postgrest
  ports:
    - "80:3000"
  environment:
    PGRST_DB_URI: <very secret postgres connection string>
    PGRST_DB_SCHEMA: api
    PGRST_DB_ANON_ROLE: web_anon
    SERVER_PORT: 80
    JWT_SECRET: <very strong jwt secret password> 
